try:
    # Empty Attack case
    pass
except Exception as e:
    log("Error: ", e)