"""
==============================================================================
ATTACK CASE: jmk9800_attackcase6.r2py
==============================================================================
Target NetID:        jmk9800
Original Test:       test18_state_tracking.r2py
Test File Path:      submit/general_tests/test18_state_tracking.r2py

RUNNER INFORMATION:
  Runner ID:         runner-8350
  Task UUID:         431bf9b6-2c47-4c9f-ae35-ac03cb4232af
  Machine Type:      t3.large
  Execution Server:  http://100.88.83.27:8000

EXECUTION INFORMATION:
  Status:            FAILED
  Start Time:        2025-10-27T19:22:48.589378
  End Time:          2025-10-27T19:22:52.898757
  Runtime:           4.3094 seconds
  Exit Code:         143

FILE HASHES:
  Monitor MD5:       f8ab597a6841526db2f6b6859e1814de
  Attack MD5:        9e0afe5edbe1306db7f522e7f8ba8e30
  Combined MD5:      2c15bb510f92c6d2d1a03588ffec3824

FAILURE DETAILS:
  Reason:            ---
Uncaught exception!
---
Following is a full traceback, and a user traceback.
The user traceback 

STDOUT:
  ---
  Uncaught exception!
  ---
  Following is a full traceback, and a user traceback.
  The user traceback excludes non-user modules. The most recent call is displayed last.
  Full debugging traceback:
    "/app/repy.py", line 134, in execute_namespace_until_completion
    "/app/virtual_namespace.py", line 116, in evaluate
    "/app/safe.py", line 610, in safe_run
    "/app/encasementlib.r2py", line 240, in <module>
    "/app/encasementlib.r2py", line 225, in secure_dispatch
    "/app/namespace.py", line 957, in __do_func_call
    "/app/namespace.py", line 1219, in wrapped_function
    "/app/virtual_namespace.py", line 116, in evaluate
    "/app/safe.py", line 610, in safe_run
    "monitor.r2py", line 129, in <module>
    "/app/encasementlib.r2py", line 175, in _secure_dispatch_closure
    "/app/encasementlib.r2py", line 225, in secure_dispatch
    "/app/namespace.py", line 957, in __do_func_call
    "/app/namespace.py", line 1219, in wrapped_function
    "/app/virtual_namespace.py", line 116, in evaluate
    "/app/safe.py", line 610, in safe_run
    "attack.r2py", line 13, in <module>
    "VMFile wrapper class", line 3, in writeat
    "wrapper.r2py", line 202, in _wrapped_func
    "monitor.r2py", line 72, in writeat
  User traceback:
    "/app/encasementlib.r2py", line 240, in <module>
    "/app/encasementlib.r2py", line 225, in secure_dispatch
    "monitor.r2py", line 129, in <module>
    "/app/encasementlib.r2py", line 175, in _secure_dispatch_closure
    "/app/encasementlib.r2py", line 225, in secure_dispatch
    "attack.r2py", line 13, in <module>
    "VMFile wrapper class", line 3, in writeat
    "wrapper.r2py", line 202, in _wrapped_func
    "monitor.r2py", line 72, in writeat
  Exception (with class 'exception_hierarchy.FileInUseError'): 
  ---

ORIGINAL TEST DESCRIPTION:
  Targets: iy2112, am14579
  Vulnerability: Improper state tracking in mycontext or version metadata
  Attack: Test file tracking across operations

==============================================================================
"""

# ============================================================================
# REFERENCE MONITOR CODE (Target: jmk9800)
# ============================================================================
# """
# This security layer inadequately handles the Versioned and Immutable functionality
# 
# Note:
#     This security layer uses encasementlib.r2py, restrictions.default, repy.py and Python
#     Also you need to give it an application to run.
#     python repy.py restrictions.default encasementlib.r2py [security_layer].r2py [attack_program].r2py 
#     
# """
# TYPE = "type"
# ARGS = "args"
# RETURN = "return"
# EXCP = "exceptions"
# TARGET = "target"
# FUNC = "func"  
# OBJC = "objc"
# 
# files = {}
# 
# class VMFile():
#     def __init__(self, filename, create):
#         self.filename = filename
#         if create:
#             found = filename.rfind(".v")
#             if found != -1:
#                 ind = filename.find(".v")
#                 ind += 2
#                 if filename[ind:].isdigit():
#                     raise RepyArgumentError("Cannot create explicit version files")
#             elif filename in listfiles():
#                 # File exists → create version 1
#                 try:
#                     prev_file = openfile(filename, False)
#                     content = prev_file.readat(None, 0)
#                     prev_file.close()
#                 except FileInUseError:
#                     raise FileInUseError
#                 else: 
#                     i = files[filename] + 1
#                     var = "v{}".format(i)
#                     new_name = filename + "." + var
#                     files[filename] += 1
#                     
#                     self.VMfile = openfile(new_name, True)
#                     self.VMfile.writeat(content, 0)
#             else:
#                 # File doesn't exist → create filename
#                 self.VMfile = openfile(filename, True)
#                 files[filename] = 0
#         else:
#             # Open existing file normally
#             try:
#                 self.VMfile = openfile(filename, False)
#             except FileNotFoundError:
#                 raise FileNotFoundError
# 
#     def readat(self, num_bytes, offset):
#         return self.VMfile.readat(num_bytes, offset)
# 
#     def writeat(self, data, offset):
#         found = self.filename.rfind(".v")
#         if found != -1:
#             ind = self.filename.rfind(".v")
#             ind += 2
#             if self.filename[ind:].isdigit():
#                 value = int(self.filename[ind:])
#                 if value < files[self.filename[:ind-2]]:
#                     raise FileInUseError
#         
#         else:
#             if self.filename in files and files[self.filename] > 0:
#                 raise FileInUseError
#             else:
#                 return self.VMfile.writeat(data, offset)
# 
#     def close(self):
#         return self.VMfile.close()
# 
# 
# def LPopenfile(filename, create):
#     return VMFile(filename, create)
# 
# def LPremovefile(filename):
#     raise RepyArgumentError
#     
# 
# def LPlistfiles():
#     all_files = []
#     for file in files.keys():
#         all_files.append(file)
#     return all_files
# 
# 
# # The code below sets up type checking and variable hiding for you.
# # You should not change anything below this point.
# sec_file_def = {
#     "obj-type": VMFile,
#     "name": "VMFile",
#     "writeat": {"type": "func", "args": (str, (int, long)), "exceptions": Exception, "return": (int, type(None)), "target": VMFile.writeat},
#     "readat": {"type": "func", "args": ((int, long, type(None)), (int, long)), "exceptions": Exception, "return": str, "target": VMFile.readat},
#     "close": {"type": "func", "args": None, "exceptions": Exception, "return": (bool, type(None)), "target": VMFile.close}
# }
# 
# CHILD_CONTEXT_DEF["openfile"] = {
#     TYPE: OBJC,
#     ARGS: (str, bool),
#     EXCP: Exception,
#     RETURN: sec_file_def,
#     TARGET: LPopenfile
# }
# 
# CHILD_CONTEXT_DEF["removefile"] = {
#     TYPE: FUNC,
#     ARGS: (str,),
#     EXCP: Exception,
#     RETURN: type(None),
#     TARGET: LPremovefile
# }
# 
# CHILD_CONTEXT_DEF["listfiles"] = {
#     TYPE: FUNC,
#     ARGS: None,
#     EXCP: Exception,
#     RETURN: list,
#     TARGET: LPlistfiles
# }
# 
# # Execute the user code
# secure_dispatch_module()
# ============================================================================

# Create a file and version it
f = openfile("tracked", True)
f.writeat("v0", 0)
f.close()

f = openfile("tracked", True)
f.writeat("v1", 0)
f.close()

# listfiles should show "tracked" (the base name)
files = listfiles()
if "tracked" not in files:
    log("ERROR: Base file missing from listfiles\n")
    exitall()

# Version files should not appear
if "tracked.v1" in files:
    log("ERROR: Version file should not appear in listfiles\n")
    exitall()

# Test reopening for read
try:
    f = openfile("tracked", False)
    content = f.readat(None, 0)
    f.close()
except FileNotFoundError:
    log("ERROR: Should be able to open existing file for reading\n")
    exitall()
